# -*- coding: utf-8 -*-
"""soal 9 juni.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sk8ApRKPMy2u9dTM0nuV_gPPch7vRarA

Implementasi AVL Tree: Insert dan Traversal
Deskripsi
"""

class AVLNode:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None
        self.height = 1


class AVLTree:

    def height(self, node):
        if not node:
            return 0
        return node.height

    def balance_factor(self, node):
        if not node:
            return 0
        return self.height(node.left) - self.height(node.right)

    def right_rotate(self, y):
        x = y.left
        t2 = x.right

        x.right = y
        y.left = t2

        y.height = max(
            self.height(y.left),
            self.height(y.right)
        ) + 1

        x.height = max(
            self.height(x.left),
            self.height(x.right)
        ) + 1

        return x

    def left_rotate(self, x):
        y = x.right
        t2 = y.left

        y.left = x
        x.right = t2

        x.height = max(
            self.height(x.left),
            self.height(x.right)
        ) + 1

        y.height = max(
            self.height(y.left),
            self.height(y.right)
        ) + 1

        return y

    def insert(self, root, key):

        if root is None:
            return AVLNode(key)

        if key < root.data:
            root.left = self.insert(root.left, key)

        elif key > root.data:
            root.right = self.insert(root.right, key)

        else:
            return root

        root.height = max(
            self.height(root.left),
            self.height(root.right)
        ) + 1

        balance = self.balance_factor(root)

        # LL
        if balance > 1 and key < root.left.data:
            return self.right_rotate(root)

        # RR
        if balance < -1 and key > root.right.data:
            return self.left_rotate(root)

        # LR
        if balance > 1 and key > root.left.data:
            root.left = self.left_rotate(root.left)
            return self.right_rotate(root)

        # RL
        if balance < -1 and key < root.right.data:
            root.right = self.right_rotate(root.right)
            return self.left_rotate(root)

        return root

    def inorder(self, root):

        if root:
            self.inorder(root.left)
            print(root.data, end=" ")
            self.inorder(root.right)


# Main Program
avl = AVLTree()
root = None

data = [30, 20, 40, 10, 25, 35]

for x in data:
    root = avl.insert(root, x)

print("Inorder Traversal:")
avl.inorder(root)

"""AVL Tree: Pencarian dan Statistik Tree Deskripsi"""

class AVLNode:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None
        self.height = 1


class AVLTree:

    def height(self, node):
        return node.height if node else 0

    def get_balance(self, node):
        return self.height(node.left) - self.height(node.right) if node else 0

    def right_rotate(self, y):
        x = y.left
        t2 = x.right

        x.right = y
        y.left = t2

        y.height = max(
            self.height(y.left),
            self.height(y.right)
        ) + 1

        x.height = max(
            self.height(x.left),
            self.height(x.right)
        ) + 1

        return x

    def left_rotate(self, x):
        y = x.right
        t2 = y.left

        y.left = x
        x.right = t2

        x.height = max(
            self.height(x.left),
            self.height(x.right)
        ) + 1

        y.height = max(
            self.height(y.left),
            self.height(y.right)
        ) + 1

        return y

    def insert(self, root, key):

        if root is None:
            return AVLNode(key)

        if key < root.data:
            root.left = self.insert(root.left, key)

        elif key > root.data:
            root.right = self.insert(root.right, key)

        else:
            return root

        root.height = max(
            self.height(root.left),
            self.height(root.right)
        ) + 1

        balance = self.get_balance(root)

        if balance > 1 and key < root.left.data:
            return self.right_rotate(root)

        if balance < -1 and key > root.right.data:
            return self.left_rotate(root)

        if balance > 1 and key > root.left.data:
            root.left = self.left_rotate(root.left)
            return self.right_rotate(root)

        if balance < -1 and key < root.right.data:
            root.right = self.right_rotate(root.right)
            return self.left_rotate(root)

        return root

    def search(self, root, key):

        if root is None:
            return False

        if root.data == key:
            return True

        if key < root.data:
            return self.search(root.left, key)

        return self.search(root.right, key)

    def count_nodes(self, root):

        if root is None:
            return 0

        return (
            1
            + self.count_nodes(root.left)
            + self.count_nodes(root.right)
        )

    def minimum(self, root):

        current = root

        while current.left:
            current = current.left

        return current.data

    def maximum(self, root):

        current = root

        while current.right:
            current = current.right

        return current.data


avl = AVLTree()
root = None

data = [50, 30, 70, 20, 40, 60, 80, 35]

for x in data:
    root = avl.insert(root, x)

key = 35

if avl.search(root, key):
    print("Data ditemukan")
else:
    print("Data tidak ditemukan")

print("Jumlah Node :", avl.count_nodes(root))
print("Tinggi Tree :", avl.height(root))
print("Minimum :", avl.minimum(root))
print("Maximum :", avl.maximum(root))

"""Implementasi Priority Queue Menggunakan Binary Heap
Deskripsi

"""

class MaxHeap:

    def __init__(self):
        self.heap = []

    def insert(self, value):

        self.heap.append(value)

        idx = len(self.heap) - 1

        while idx > 0:

            parent = (idx - 1) // 2

            if self.heap[parent] < self.heap[idx]:

                self.heap[parent], self.heap[idx] = (
                    self.heap[idx],
                    self.heap[parent]
                )

                idx = parent
            else:
                break

    def extract_max(self):

        if not self.heap:
            return None

        maximum = self.heap[0]

        self.heap[0] = self.heap[-1]
        self.heap.pop()

        idx = 0

        while True:

            left = 2 * idx + 1
            right = 2 * idx + 2
            largest = idx

            if (
                left < len(self.heap)
                and self.heap[left] > self.heap[largest]
            ):
                largest = left

            if (
                right < len(self.heap)
                and self.heap[right] > self.heap[largest]
            ):
                largest = right

            if largest != idx:
                self.heap[idx], self.heap[largest] = (
                    self.heap[largest],
                    self.heap[idx]
                )
                idx = largest
            else:
                break

        return maximum

    def display(self):
        print(self.heap)


heap = MaxHeap()

heap.insert(20)
heap.insert(15)
heap.insert(40)
heap.insert(10)

heap.display()

print("Data terbesar =", heap.extract_max())

heap.display()

"""Implementasi Trie Dictionary
Deskripsi

5. project Smart Search Engine Menggunakan AVL Tree + Binary Heap + Trie
Deskripsi
"""

import heapq

# =====================
# DOCUMENT
# =====================

class Document:

    def __init__(self, doc_id, title, score):

        self.id = doc_id
        self.title = title
        self.score = score


# =====================
# AVL TREE
# =====================

class AVLNode:

    def __init__(self, document):

        self.doc = document
        self.left = None
        self.right = None
        self.height = 1


class AVLTree:

    def height(self, node):
        return node.height if node else 0

    def balance(self, node):

        if not node:
            return 0

        return (
            self.height(node.left)
            - self.height(node.right)
        )

    def right_rotate(self, y):

        x = y.left
        t2 = x.right

        x.right = y
        y.left = t2

        y.height = max(
            self.height(y.left),
            self.height(y.right)
        ) + 1

        x.height = max(
            self.height(x.left),
            self.height(x.right)
        ) + 1

        return x

    def left_rotate(self, x):

        y = x.right
        t2 = y.left

        y.left = x
        x.right = t2

        x.height = max(
            self.height(x.left),
            self.height(x.right)
        ) + 1

        y.height = max(
            self.height(y.left),
            self.height(y.right)
        ) + 1

        return y

    def insert(self, root, document):

        if root is None:
            return AVLNode(document)

        if document.id < root.doc.id:
            root.left = self.insert(root.left, document)

        elif document.id > root.doc.id:
            root.right = self.insert(root.right, document)

        else:
            return root

        root.height = max(
            self.height(root.left),
            self.height(root.right)
        ) + 1

        bf = self.balance(root)

        if bf > 1 and document.id < root.left.doc.id:
            return self.right_rotate(root)

        if bf < -1 and document.id > root.right.doc.id:
            return self.left_rotate(root)

        if bf > 1 and document.id > root.left.doc.id:
            root.left = self.left_rotate(root.left)
            return self.right_rotate(root)

        if bf < -1 and document.id < root.right.doc.id:
            root.right = self.right_rotate(root.right)
            return self.left_rotate(root)

        return root

    def search(self, root, doc_id):

        if root is None:
            return None

        if root.doc.id == doc_id:
            return root.doc

        if doc_id < root.doc.id:
            return self.search(root.left, doc_id)

        return self.search(root.right, doc_id)

    def inorder(self, root):

        if root:

            self.inorder(root.left)

            print(
                root.doc.id,
                root.doc.title,
                root.doc.score
            )

            self.inorder(root.right)


# =====================
# TRIE
# =====================

class TrieNode:

    def __init__(self):
        self.children = {}
        self.words = []


class Trie:

    def __init__(self):
        self.root = TrieNode()

    def insert(self, word):

        node = self.root

        for char in word.lower():

            if char not in node.children:
                node.children[char] = TrieNode()

            node = node.children[char]
            node.words.append(word)

    def autocomplete(self, prefix):

        node = self.root

        for char in prefix.lower():

            if char not in node.children:
                return []

            node = node.children[char]

        return node.words


# =====================
# SEARCH ENGINE
# =====================

avl = AVLTree()
trie = Trie()

root = None

maxheap = []

while True:

    print("\n===== MENU =====")
    print("1. Tambah Dokumen")
    print("2. Cari Dokumen")
    print("3. Autocomplete")
    print("4. Top K Dokumen")
    print("5. Tampilkan Semua")
    print("6. Keluar")

    pilihan = input("Pilih : ")

    if pilihan == "1":

        doc_id = int(input("ID : "))
        title = input("Judul : ")
        score = int(input("Score : "))

        doc = Document(
            doc_id,
            title,
            score
        )

        root = avl.insert(root, doc)

        trie.insert(title)

        heapq.heappush(
            maxheap,
            (-score, title)
        )

        print("Dokumen ditambahkan")

    elif pilihan == "2":

        doc_id = int(input("Cari ID : "))

        hasil = avl.search(
            root,
            doc_id
        )

        if hasil:
            print(
                hasil.id,
                hasil.title,
                hasil.score
            )
        else:
            print("Tidak ditemukan")

    elif pilihan == "3":

        prefix = input("Prefix : ")

        hasil = trie.autocomplete(prefix)

        if hasil:
            for h in hasil:
                print(h)
        else:
            print("Tidak ada")

    elif pilihan == "4":

        k = int(input("Top K = "))

        temp = sorted(maxheap)

        for i in range(
            min(k, len(temp))
        ):
            score, title = temp[i]

            print(
                title,
                "Score =",
                -score
            )

    elif pilihan == "5":

        avl.inorder(root)

    elif pilihan == "6":

        print("Program selesai")
        break

    else:
        print("Menu tidak valid")